package com.example.task_manager.security;

public class SecurityConstants {
    public static final long JWT_EXPIRATION = 70000;
    public static final String JWT_SECRET = "dkaxtkisogoxdfkvucxzrqootgxymxxylxifimjeomxphfcloupdstownkdgqkrfhkwtuvsgpxvrpcmuvnijyfqjddkzteybuqdfafakzfhpcialetvcuguubfehhrlmtubcmwttwyledgzzpildoultanorsjmfdrjrrvinxxhlhlzniftqnkuavbfzxkhcpvhwqziwnjypvfhmpsrefudhnfgihpysbnsokqpnabofvxofrjlhyzncohpwdgxb";
}
